w3c/spec-generator

generators/respec.js
=> don't always timeout; use stderr only

lib/w3c-metadata.js
Fixed undefined bug and regex shortcomings 	
Use obsoletes for previousVersion if same date
=> Missing shortname and previousVersion error

generators/respec.js
This will resolve the stdout maxBuffer exceeded error.
=> Increase the buffer to satisfy appmanifest

generators/respec.js
Fixes https://github.com/w3c/spec-generator/issues/22
=> Now using spawn

package.json
=> fix(package): update respec to version 18.0.3

package.json
=> fix(package): update respec to version 18.1.2

package.json
=> fix(package): update respec to version 18.2.0

package.json
=> fix(package): update respec to version 18.3.0

package.json
=> fix(package): update respec to version 19.0.1

package.json
=> fix(package): update respec to version 19.2.2

generators/respec.js, package.json
=> fix(package): update respec to version 19.4.0

package.json
=> fix(package): update respec to version 20.0.4

package.json
=> fix(package): update respec to version 20.2.2

package.json
=> fix(package): update respec to version 20.7.2

.travis.yml, package.json
Adds a personalized github token, which grants 5000 request per hour.
=>  ci(travis): authorize github requests

package.json
=> fix(package): update respec to version 20.11.2

package.json
=> fix(package): update respec to version 22.3.3

package.json
=> fix(package): update respec to version 22.5.2

package.json
=> fix(package): update respec to version 23.0.1

package.json
=> fix(package): update respec to version 23.0.5

package.json
=> fix(package): update respec to version 23.3.0

package.json
=> fix(package): update respec to version 23.6.0

generators/respec.js, server.js, test/test.js
=> fix(generators/respec): use & not ;

package.json
=> fix(package): update respec to version 23.7.4

package.json
=> fix(package): update respec to version 24.2.0

package.json
=> fix(package): update respec to version 24.2.4

package.json
=> fix(package): update respec to version 24.3.4

package.json
=> fix(package): update respec to version 24.4.5

package.json
=> fix(package): update respec to version 24.7.0

package.json
=> fix(package): update respec to version 24.9.1

package.json
=> fix(package): update respec to version 24.13.0

package.json
=> fix(package): update respec to version 24.21.4

package.json
=> fix(package): update respec to version 24.21.7

package.json
=> fix(package): update express to version 4.17.1

package.json
=> fix(package): update respec to version 24.22.2

package.json
=> fix(package): update respec to version 24.23.4

package.json
=> fix(package): update respec to version 24.28.0

package.json
=> fix(package): update respec to version 24.32.1

package.json
=> fix(package): update respec to version 24.33.1

package.json
=> fix(package): update respec to version 24.35.0

package.json
=> fix(package): update respec to version 24.38.1

package.json
=> fix(package): update respec to version 25.0.1

package.json
=> fix(package): update respec to version 25.1.0

package.json
=> fix(package): update respec to version 25.8.1

test/test.js
Missed this in https://github.com/w3c/spec-generator/pull/344
=> Remove githubToken, githubUser params from tests

.prettierrc, server.js
This is essentially a rewrite, so the PR is large. Consider reviewing commit by commit. Later, a sanity check on final `server.js` would also make sense.
As a summary:
- I've extracted some functions to make code more readable.
- Converted `var` to `let`/`const`, made formatting consistent (using prettier).
- Move all imports to top of module.
- And some general refactoring (use async await etc.).
- Improved input validation a bit.
Let me know if you'd like me to send this as separate PRs, though I've tried to keep separate commits sane enough.
=> rerfactor server.js to use modern and cleaner code

.travis.yml, generators/respec.js, package.json
Closes https://github.com/w3c/spec-generator/pull/352
=> Update ReSpec to v25.18.1

index.html, server.js, test/test.js
Closes https://github.com/w3c/spec-generator/issues/138
=> Add a form to submit URL or upload file

.github/workflows/lint.yml, package.json
=> Add Node@16

generators/respec.js, package.json, server.js, test/test.js
=> rework #512 and migrate to ESM

package.json, server.js
=> fix encoding issue for specs hosted on githubusercontent

server.js
=> fix ED generation when it's hosted on raw.githubusercontent.com

package.json
closes https://github.com/w3c/spec-generator/pull/586/files
=> Upgrade tar stream to 3.0.0

server.js
Fixes [example](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2FWICG%2Fwebmonetization%2Fa21eb5e4c1ddfaa6344ba2a40f07ae2daca6e117%2Fsrc%2Fpages%2Fspecification%2Fspecification-respec.html#checking-if-web-monetization-is-supported)
| Before | After (localhost) |
| --- | --- |
| ![includes 404](https://github.com/user-attachments/assets/4416e8e5-c6e2-4e5d-ac0f-14dbda7aac07) | ![includes work](https://github.com/user-attachments/assets/0e0ade61-a44f-48df-bc93-5a34dc54f1a6) |
=> feat: download respec data-include files for GitHub links
